name: starlight_messenger
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  firebase_storage: ^11.2.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  provider: ^6.1.1
  flutter:
    sdk: flutter
  cloud_firestore: ^4.14.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
