// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXX1orttvU1UECRChs5jyg5aWd3PObnrE',
    appId: '1:419717344316:web:e7eeb10cf91e0c6197e739',
    messagingSenderId: '419717344316',
    projectId: 'starlight-eae36',
    authDomain: 'starlight-eae36.firebaseapp.com',
    storageBucket: 'starlight-eae36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkyKU4rgdboPbQb0YzFHOoE2N11LW7-8I',
    appId: '1:419717344316:android:89693cfa64e9727f97e739',
    messagingSenderId: '419717344316',
    projectId: 'starlight-eae36',
    storageBucket: 'starlight-eae36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4avcN6ABqFcTPFdUYVqSrWOn7drRJwp0',
    appId: '1:419717344316:ios:8d0a371b5d643a8397e739',
    messagingSenderId: '419717344316',
    projectId: 'starlight-eae36',
    storageBucket: 'starlight-eae36.appspot.com',
    iosBundleId: 'com.example.starlightMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4avcN6ABqFcTPFdUYVqSrWOn7drRJwp0',
    appId: '1:419717344316:ios:1cb614ab04a1a88d97e739',
    messagingSenderId: '419717344316',
    projectId: 'starlight-eae36',
    storageBucket: 'starlight-eae36.appspot.com',
    iosBundleId: 'com.example.starlightMessenger.RunnerTests',
  );
}
